// features/workout/hooks/useActiveWorkout.ts
import { useUser } from "@clerk/clerk-expo";
import { useWorkoutStore } from "../../../store/workoutStore";
import type { Exercise, WorkoutSet, WorkoutTemplate } from "../../../types/workout";
import { supabase } from "../../../services/supabase/client";

export const useActiveWorkout = () => {
  const { user } = useUser();
  const {
    activeWorkout,
    isWorkoutActive,
    workoutStartTime,
    isLoading,
    error,
    startWorkout,
    endWorkout,
    addExercise,
    removeExercise,
    updateExercise,
    addSet,
    updateSet,
    deleteSet,
    toggleSetCompletion,
    saveWorkout,
  } = useWorkoutStore();

  const createWorkout = (name: string) => {
    if (!user?.id) {
      console.error("User not authenticated");
      return;
    }
    startWorkout(name, user.id);
  };

  const addExerciseToWorkout = (exerciseName: string, exerciseId: string) => {
    const newExercise: Exercise = {
      id: Date.now().toString(),
      name: exerciseName,
      muscleGroup: "",
      sets: [],
      notes: "",
    };
    addExercise(newExercise);
  };

  const addNewSet = (exerciseId: string, previousSet?: WorkoutSet) => {
    const newSet: WorkoutSet = {
      id: Date.now().toString(),
      setNumber:
        activeWorkout?.exercises.find((ex) => ex.id === exerciseId)?.sets
          .length || 0 + 1,
      type: "normal",
      weight: previousSet?.weight || 0,
      reps: previousSet?.reps || 0,
      completed: false,
      restTime: 90,
    };
    addSet(exerciseId, newSet);
  };

  const finishWorkout = async () => {
    if (!activeWorkout || !user) return;
    await saveWorkout();
  };

  const saveAsTemplate = async (
    template: Omit<WorkoutTemplate, 'id' | 'createdAt' | 'updatedAt'>
  ) => {
    try {
      if (!activeWorkout?.userId) {
        throw new Error('User ID not found');
      }

      const now = new Date().toISOString();

      // Don't include 'id' - let the database generate it
      const { data, error } = await supabase
        .from('workout_templates')
        .insert({
          // id is auto-generated by database (UUID or auto-increment)
          name: template.name,
          exercises: template.exercises,
          user_id: activeWorkout.userId,
          created_at: now,
          updated_at: now,
        })
        .select()
        .single();

      if (error) throw error;

      console.log('✅ Template saved:', data);
      return data;
    } catch (error) {
      console.error('Error saving template:', error);
      throw error;
    }
  };


  return {
    activeWorkout,
    isWorkoutActive,
    workoutStartTime,
    isLoading,
    error,
    createWorkout,
    endWorkout: finishWorkout,
    addExerciseToWorkout,
    removeExercise,
    updateExercise,
    addNewSet,
    updateSet,
    deleteSet,
    toggleSetCompletion,
    saveAsTemplate,
  };
};
